import { Link } from 'react-router-dom';
import jobCatalog from "../assets/images/JobCatalogue.jpg";
import aiScreening from "../assets/images/AI.png";
import onlineExam from "../assets/images/AI-quiz.png";
import hrReview from "../assets/images/HR-Manager.png";

export default function Home() {
  return (
    <main className="home">
      <section className="hero-section">
        <div className="hero-content">
          <h1>Fly Your Career Forward</h1>
          <p>
            Join Ethiopian Airlines — Africa's fastest-growing airline. We use
            AI-powered screening to find the best talent, quickly and fairly.
          </p>
          <div className="hero-actions">
            <Link to="/jobs" className="btn-primary btn-lg">Browse Open Positions</Link>
            <Link to="/register" className="btn-outline btn-lg">Create Account</Link>
          </div>
        </div>
      </section>

      {/* <section className="how-it-works">
        <h2>How It Works</h2>
        <div className="steps">
          <div className="step">
            <span className="step-num">1</span>
            <h3>Browse Jobs</h3>
            <p>Explore open positions across all departments and locations.</p>
          </div>
          <div className="step">
            <span className="step-num">2</span>
            <h3>Submit Your CV</h3>
            <p>Upload your PDF CV and write a short cover letter.</p>
          </div>
          <div className="step">
            <span className="step-num">3</span>
            <h3>AI Screening</h3>
            <p>Our AI reads your CV, scores it, and invites the best candidates to an exam.</p>
          </div>
          <div className="step">
            <span className="step-num">4</span>
            <h3>Take the Exam</h3>
            <p>Complete a role-specific exam generated by AI.</p>
          </div>
          <div className="step">
            <span className="step-num">5</span>
            <h3>HR Review</h3>
            <p>Top candidates are surfaced to HR for final decisions.</p>
          </div>
        </div>
      </section> */}
      <section className="how-it-works">
  <h1>How It 
    <span> Works</span>
  </h1>

  <div className="work-row">
    <div className="work-content">
      <h3> Jobs
        <span> Browse</span>
      </h3>
      <p>
        Explore opportunities across Ethiopian Airlines departments,
        including engineering, cabin crew, IT, customer service,
        administration, and more. Find a position that matches your
        skills and career goals.
      </p>
    </div>

    <div className="work-image">

      <img src={jobCatalog} alt="Browse Jobs" />
      
    </div>
  </div>

  <div className="work-row reverse">
    <div className="work-image">
      <img src={aiScreening} alt="AI Screening" />
    </div>

    <div className="work-content">
      <h3>AI 
        <span>  Screening</span>
      </h3>
      <p>
        Our intelligent screening system analyzes CVs and qualifications
        to identify the most suitable candidates. This ensures a faster,
        fairer, and more accurate recruitment process.
      </p>
    </div>
  </div>

  <div className="work-row">
    <div className="work-content">
      <h3>Take the 
        <span> Exam</span>
      </h3>
      <p>
        Qualified applicants are invited to complete an online assessment
        designed specifically for the role they applied for.
      </p>
    </div>

    <div className="work-image">
      <img src={onlineExam} alt="Online Exam" />
    </div>
  </div>

  <div className="work-row reverse">
    <div className="work-image">
      <img src={hrReview} alt="HR Review" />
    </div>

    <div className="work-content">
      <h3>HR <span>Review</span></h3>
      <p>
        Top-performing candidates are reviewed by HR specialists who make
        the final hiring decisions and contact successful applicants.
      </p>
    </div>
  </div>
</section>
    </main>
  );
}
